### ISSUE TITLE
Issue with Wordpress  version 4.8

### ISSUE THREAD

**Issue by kgozman** [alhazmy13/Contact-Form-7-Submission-limit#1]
Not limiting contact form submissions 
only visible error is 

AddUpdate Settings

Warning: Invalid argument supplied for foreach() in /home/.../wp-content/plugins/contact-form-7-submission-limit/contact-form-7-submission-limit.php on line 355

**Comment by alhazmy13** [comment]
I'll look to it, Thanks @kgozman

**Comment by kgozman** [comment]
Hey, so it looks like WP 4.8 change some of the table names

**Comment by kgozman** [comment]
OOps lol,. sorry
i think this may resolve the issue for line 344 or there abouts

    $string = 'SELECT ' . $wpdb->prefix . 'posts.`ID`,   form_post_id,count(DISTINCT `form_date`)   as count FROM  ' . $wpdb->prefix . 'db7_forms join ' . $wpdb->prefix . 'posts where ' . $wpdb->prefix . 'db7_forms.`form_post_id` = ' . $wpdb->prefix . 'posts.`ID` group by form_id';

**Comment by kgozman** [comment]
looks like there maybe other things going on

**Comment by kgozman** [comment]
im also trying to do two forms
it looks like this line replaces all forms

                $pattern = "/<form\b[^>]*[class=\"wpcf7\-form\-$find\"]\b[^>]*>(.*?)<\/form>/is{1}";
                $buffer = preg_replace($pattern, $cf7sl_settings['cf7slreplace'][$key], $buffer);

i added an id to the class in contact-form.php ... 		$class = 'wpcf7-form-' . $this->id;

so the form now has class name with an id

but still matches both :/

**Comment by kgozman** [comment]
This seems to be working better

                $pattern = "/<form\b[^>]*(class=\"wpcf7\-form\-($find))\b[^>]*>(.*?)<\/form>/is";

**Comment by alhazmy13** [comment]
Hi @kgozman 
Thanks for your report and for your help, can you please check version [1.0.2](https://github.com/alhazmy13/Contact-Form-7-Submission-limit/releases/tag/v1.0.2) and let me know if it fixes your problem or not.

Thanks
