### ISSUE TITLE
Can't "add" a rule

### ISSUE THREAD

**Issue by bilbo15** [alhazmy13/Contact-Form-7-Submission-limit#3]
At first, thanks for the Plugin. I really like what it should do.

Not sure if this is the right spot to ask for "support".
I installed the plugin and got CF7 as well as CFDB Plugin.

But when I try to press the "Add" Button for a new rule (limitation), nothing happens.
Neither I see a dropdown for choosing a Form.

If I hit the "Update Settings" Button it just says "options updated".

I've got WP 4.8 Version.

Thanks for help!

**Comment by alhazmy13** [comment]
Hi @bilbo15 

Are you in version [1.0.2](https://github.com/alhazmy13/Contact-Form-7-Submission-limit/releases/tag/v1.0.2) ? Because there's was an issue with the previous version.

**Comment by bilbo15** [comment]
Hi @alhazmy13 ,

I redownloaded it after the adjustments from earlier this day.

Did it again with your link. Seems to work out now.

Thanks alot!

**Comment by alhazmy13** [comment]
Glad to hear this from you.
